stories/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.StoryList.as_view(), name='home'),
    path('', views.HeadlineList.as_view(), name='home')
]

tfstories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('stories.urls'), name='stories_urls'),
]

stories/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))

class Story(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    excerpt = models.TextField(blank=True)
    featured_image = CloudinaryField('image', default='placeholder')
    status = models.IntegerField(choices=STATUS, default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stories')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, unique=True)
    tvote = models.ManyToManyField(User, related_name='story_tvote', blank=True)
    fvote = models.ManyToManyField(User, related_name='story_fvote', blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def number_of_tvotes(self):
        return self.tvote.count()

    def number_of_fvotes(self):
        return self.fvote.count()


class Comment(models.Model):
    post = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'


class Headline(models.Model):
    title = models.CharField(max_length=100, unique=True)
    content = models.TextField()
    displayed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

stories/views.py
from django.shortcuts import render
from django.views import generic
from .models import Story, Headline


class StoryList(generic.ListView):
    model = Story
    queryset = Story.objects.filter(status=1).order_by('-created')
    template_name = 'index.html'
    paginate_by = 6


class HeadlineList(generic.ListView):
    model = Headline
    queryset = Headline.objects.filter(displayed=True).order_by('-created')
    template_name = 'index.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" type="text/css" />

  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css"
    integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

  <title>True or False</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">true or false</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Story List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
  </main>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<!--Cover image and story cards section-->
<section>
    <div class="container-fluid cover-img">
        <div class="row">
            <div class="col-md-3">
                <div class="card story-card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Special title treatment</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
            </div>
            <div class="col-md-3">
                <div class="card story-card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Special title treatment</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 story-card">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Special title treatment</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
            </div>
            <div class="col-md-3 story-card">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Special title treatment</h5>
                        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Story list section-->
<section>
    <div class="container" id="story-list-cont">
        <div class="list-group">
            {% for story in story_list %}
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ story.title }}</h5>
                    <small>
                        {{ story.number_of_tvotes }} voted True<br>
                        {{ story.number_of_fvotes }} voted False
                    </small>
                </div>
                <p class="mb-1">{{ story.excerpt }}</p>
                <small>{{ story.author }} {{ story.created }}</small>
            </a>
            {% endfor %}
        </div>
    </div>
</section>

{%endblock%}